version: '2'

services:
  haproxy:
    image: haproxy:1.7
    volumes:
      - ./service/haproxy/config:/usr/local/etc/haproxy
    ports:
      - 80:80
      - 443:443
    networks:
      front-tier:
        aliases:
          - haproxy
      back-tier:

  couchbase:
    image: couchbase:latest
    volumes:
      - ./service/couchbase:/opt/couchbase/var
    ports:
      - 8091-8094:8091-8094
      - 11207:11207
      - 11210:11210
      - 11211:11211
    entrypoint: /opt/couchbase/var/entrypoint.sh
    networks:
      back-tier:
        aliases:
          - couchbase

  mariadb:
    image: mariadb:10.3
    volumes:
      - ./service/mariadb/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ridi
      MYSQL_USER: ridi
      MYSQL_PASSWORD: ridi
      MYSQL_DATABASE: cms
    networks:
      front-tier:
      back-tier:
        aliases:
          - mariadb

  main:
    image: ridibooks/cms:latest
    ports:
      - 0:80
    env_file:
      - ./service/cms/.env
    networks:
      back-tier:
        aliases:
          - cms_main

  admin:
    image: ridibooks/cms-admin:latest
    ports:
      - 0:80
    env_file:
      - ./service/cms-admin/.env
    networks:
      back-tier:
        aliases:
          - cms_admin

  example:
    image: ridibooks/performance-apache-base:latest
    volumes:
      - ./service/example:/var/www/html
    environment:
      APACHE_DOC_ROOT: /var/www/html/web
      XDEBUG_ENABLE: 1
    ports:
      - 0:80
    networks:
      back-tier:
        aliases:
          - cms_example

networks:
  front-tier:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.0.0/24
  back-tier:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.1.0/24
