version: '2'
services:
  haproxy:
    image: haproxy:1.7
    volumes:
      - ./haproxy/config:/usr/local/etc/haproxy
    ports:
      - 80:80
    networks:
      my_net:
        ipv4_address: 172.16.0.2
  admin:
    image: ridibooks/cms-admin
    volumes:
      - ./cms-admin/config:/var/cms-admin
    ports:
      - 800:80
    networks:
      my_net:
        ipv4_address: 172.16.0.3
  cms:
    image: ridibooks/cms
    volumes:
      - ./cms/config:/var/cms
    ports:
      - 900:80
    networks:
      my_net:
        ipv4_address: 172.16.0.4
  couchbase:
    image: couchbase:latest
    volumes:
      - ./couchbase:/opt/couchbase/var
    ports:
      - 8091-8094:8091-8094
      - 11207:11207
      - 11210:11210
      - 11211:11211
    networks:
      my_net:
        ipv4_address: 172.16.0.5
networks:
  my_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24
